### ISSUE TITLE
Query for Vercel Team members, wait for ready state 

### ISSUE THREAD

**Issue by lukestanley** [mikefrancis/vercel-cypress#1]
We use Vercel in a team setting so I added an extra parameter to the Curl command, and I added a command that checks for a "READY" state also:
https://github.com/kendraio/kendraio-app/blob/4aaa6413d8c9200c8b5443c4ce6c1f413c99f072/.github/actions/e2e/entrypoint.sh

https://github.com/kendraio/kendraio-app/blob/4aaa6413d8c9200c8b5443c4ce6c1f413c99f072/.github/workflows/vercel_deployment_tests.yml

I don't know if the same request would work for non-team Vercel API users.
I wasn't sure what (if anything) you'd like doing with my modifications, or how you'd like crediting, please let me know.
Obviously do what you like with the minor changes.

**Comment by mikefrancis** [comment]
Hey @lukestanley,

Thanks for passing that on. 

Curious to know what changes you needed to make it work for teams?

**Comment by lukestanley** [comment]
I think the only difference I did there, which made it show up was adding "&teamId=kendraio" to the repo name (so it became "kendraio-app&teamId=kendraio")
Without adding it, the deployments key was an empty array.
It's hard to see without looking at both the flow that specifies it, bit of a hack as I was trying hard to avoid changing your code unless I had to. I suppose it would be better to make it explicit.

Our build takes 2 minutes, so I had to add the wait loop too.
Interestingly, unfortunately Vercel provides a  response with a 200 status code from Vercel.com before the subdomain has the app deployed, so I couldn't use a more standard npm package for this and the Curl loop seemed the best way.
This way at least it can install things ready (to defend burning CI minutes).
Maybe there is a better hook I could have used than the on "deployment" hook too.
If I had more time, I suppose a better prebuild Docker image would be avoid having to run npm install on test runtime, or at least a more selective set of npm package installs, and avoid running out of minutes, but I've not hit a limit yet anyhow. :)

**Comment by mikefrancis** [comment]
@lukestanley OK, thanks for the detailed description 😄 

If you're up for it, I think the way to go if just make another action input for team name, and append the cURL request URL if it's there.

Completely up to you if you want to submit a PR for it!
